# Generated by Django 4.2.7 on 2024-07-12 23:30
# django generated a script to drop field instead of renaming it

from django.conf import settings
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfollowing",
            old_name="user_id",
            new_name="user",
        )
    ]
